services:
  mongodb:
    image: mongo:8
    container_name: livraria-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: livraria
    volumes:
      - livraria-mongodb-data:/data/db

volumes:
  livraria-mongodb-data:
